[package]
name = "rusty_chip"
version = "0.1.0"
authors = ["quelledanielle <quelledanielle@users.noreply.github.com>"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.5"
